# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJvGbANrnFBmBY-t3tLfXfZjH-T0cWfE
"""

import streamlit as st
import pandas as pd
from streamlit_folium import st_folium
# Import fungsi dari file hitung_spasial.py
from script import run_spatial_analysis

# Konfigurasi Halaman (Lebar penuh untuk meniru layout 2 kolom di Excel)
st.set_page_config(layout="wide", page_title="PPAC Spatial Dashboard")

# Opsi Dropdown untuk tipe kendaraan
MODE_OPTIONS = ["BERJALAN", "MOTOR", "MOBIL"]

# Membuat 2 Kolom Utama (Kiri: PPAC, Kanan: RESULT)
col_left, col_right = st.columns([1, 1.5])

with col_left:
    st.markdown("<h2 style='text-align: center; border: 2px solid black; padding: 10px;'>PPAC</h2>", unsafe_allow_html=True)

    # --- KOORDINAT ---
    st.markdown("#### KOORDINAT")
    lat_input = st.number_input("LATITUDE", value=-6.272089, format="%.6f")
    lon_input = st.number_input("LONGITUDE", value=106.800942, format="%.6f")

    st.markdown("---")

    # --- RADIUS ---
    st.markdown("#### RADIUS")
    col_rad1, col_rad2 = st.columns(2)
    with col_rad1:
        radius_1 = st.number_input("RADIUS I (M)", value=400, step=100)
    with col_rad2:
        radius_2 = st.number_input("RADIUS II (M)", value=800, step=100)

    st.markdown("---")

    # --- ISOCHRONE ---
    st.markdown("#### ISO")

    # Target
    st.write("**TARGET**")
    col_t1, col_t2 = st.columns(2)
    with col_t1:
        iso_time_target = st.number_input("MINUTES (TARGET)", value=10, min_value=1)
    with col_t2:
        iso_mode_target = st.selectbox("TIPE (TARGET)", MODE_OPTIONS, index=1) # Default MOTOR

    # Clone
    st.write("**CLONE**")
    col_c1, col_c2 = st.columns(2)
    with col_c1:
        iso_time_clone = st.number_input("MINUTES (CLONE)", value=2, min_value=1)
    with col_c2:
        iso_mode_clone = st.selectbox("TIPE (CLONE)", MODE_OPTIONS, index=1)

    # Competitor
    st.write("**COMPETITOR**")
    col_co1, col_co2 = st.columns(2)
    with col_co1:
        iso_time_comp = st.number_input("MINUTES (COMPETITOR)", value=4, min_value=1)
    with col_co2:
        iso_mode_comp = st.selectbox("TIPE (COMPETITOR)", MODE_OPTIONS, index=1)

    st.write("") # Spacer
    run_button = st.button("RUN", use_container_width=True)

with col_right:
    st.markdown("<h2 style='text-align: center; border: 2px solid black; padding: 10px;'>RESULT</h2>", unsafe_allow_html=True)

    # Jika tombol RUN ditekan atau session state sudah memiliki data
    if run_button:
        with st.spinner('Menghitung data spasial...'):
            # Memanggil fungsi dari hitung_spasial.py
            df_toko, df_area, m_folium, kml_data = run_spatial_analysis(
                lat=lat_input,
                lon=lon_input,
                radius1=radius_1,
                radius2=radius_2,
                iso_time_target=iso_time_target,
                iso_mode_target=iso_mode_target,
                iso_time_clone=iso_time_clone,
                iso_mode_clone=iso_mode_clone,
                iso_time_comp=iso_time_comp,
                iso_mode_comp=iso_mode_comp
            )

            # Menyimpan hasil ke session_state agar tidak hilang saat re-render (misal saat download)
            st.session_state['df_toko'] = df_toko
            st.session_state['df_area'] = df_area
            st.session_state['m_folium'] = m_folium
            st.session_state['kml_data'] = kml_data

    # Menampilkan hasil jika sudah ada di session_state
    if 'df_toko' in st.session_state:
        st.write("##### TOKO KOMPETITOR/CLONE VALID (DALAM RADIUS 800M)")
        st.dataframe(st.session_state['df_toko'], use_container_width=True, hide_index=True)

        st.write("##### TABEL AREA COVERAGE")
        st.dataframe(st.session_state['df_area'], use_container_width=True, hide_index=True)

        st.write("##### MAP")
        # Menampilkan peta folium
        st_folium(st.session_state['m_folium'], width=700, height=400)

        # Tombol Download KML
        st.download_button(
            label="DOWNLOAD MAP AS KML",
            data=st.session_state['kml_data'],
            file_name="coverage_map.kml",
            mime="application/vnd.google-earth.kml+xml",
        )
    else:
        st.info("Silakan isi parameter di kolom PPAC dan tekan tombol RUN untuk melihat hasil.")
