# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJvGbANrnFBmBY-t3tLfXfZjH-T0cWfE
"""

import os
import requests
import warnings
import geopandas as gpd
import pandas as pd
import numpy as np
from shapely.geometry import Point
import ee
import osmnx as ox
import networkx as nx
import folium
import streamlit as st
warnings.filterwarnings('ignore')

def run_spatial_analysis(lat, lon, radius1, radius2,
                         iso_time_target, iso_mode_target,
                         iso_time_clone, iso_mode_clone,
                         iso_time_comp, iso_mode_comp):
    """
    Fungsi utama untuk memproses logic spatial coverage, isochrone, dan Huff Model.
    Parameter diambil dari inputan user di Streamlit.
    """

    # ==========================================
    # 1. KONFIGURASI PARAMETER
    # ==========================================
    SPEED_DICT = {
        'BERJALAN': 5,
        'MOTOR': 15,
        'MOBIL': 30
    }

    # ==========================================
    # 2. INISIALISASI & SETUP LINGKUNGAN
    # ==========================================
    print("="*50)
    print("MEMULAI PROSES LOCATION INTELLIGENCE")
    print("="*50)

    # A. Setup Google API (Places & Geocoding)
    # Mengambil key langsung dari st.secrets
    try:
        API_KEY = st.secrets["GOOGLE_API_KEY"]
        USE_GOOGLE_API = True
        print("✅ API Key berhasil dimuat dari st.secrets!")
    except KeyError:
        API_KEY = None
        USE_GOOGLE_API = False
        print("⚠️ WARNING: GOOGLE_API_KEY tidak ditemukan di secrets. Menggunakan fallback data.")

    # B. Setup Earth Engine
    GCP_PROJECT_ID = 'project-ppac'
    
    try:
        # 1. Ambil data JSON Service Account dari st.secrets lu
        key_dict = dict(st.secrets["gcp_service_account"])
        
        # 2. Ubah formatnya jadi kredensial OAuth2 Google
        from google.oauth2 import service_account
        credentials = service_account.Credentials.from_service_account_info(key_dict)
        scoped_credentials = credentials.with_scopes([
            'https://www.googleapis.com/auth/earthengine',
            'https://www.googleapis.com/auth/cloud-platform'
        ])
        
        # 3. Masukkan kredensial ini langsung ke Initialize (TANPA ee.Authenticate!)
        ee.Initialize(credentials=scoped_credentials, project=GCP_PROJECT_ID)
        print("✅ Earth Engine berhasil diinisialisasi menggunakan Service Account!")
        
    except KeyError:
        st.error("⚠️ Kunci [gcp_service_account] belum ada di pengaturan st.secrets Streamlit!")
    except Exception as e:
        st.error(f"⚠️ Gagal inisialisasi GEE: {e}")

    pt_target = Point(lon, lat)
    gdf_center = gpd.GeoDataFrame(geometry=[pt_target], crs='EPSG:4326')
    gdf_center_metric = gdf_center.to_crs('EPSG:3857')
    center_geom_metric = gdf_center_metric.geometry.iloc[0]

    buffer_radius_1 = gdf_center_metric.buffer(radius1).to_crs('EPSG:4326').iloc[0]
    buffer_radius_2 = gdf_center_metric.buffer(radius2).to_crs('EPSG:4326').iloc[0]

    # ==========================================
    # 3. MENGUNDUH NETWORK GRAPH BERDASARKAN MODE
    # ==========================================
    print("Membangun Network Graph via OSMnx...")
    modes_needed = {iso_mode_target, iso_mode_comp, iso_mode_clone}
    graphs = {}
    dist_network = max(radius2 + 1000, 2000)

    if 'BERJALAN' in modes_needed:
        graphs['BERJALAN'] = ox.graph_from_point((lat, lon), dist=dist_network, network_type='walk')

    if 'MOTOR' in modes_needed or 'MOBIL' in modes_needed:
        graphs['DRIVE'] = ox.graph_from_point((lat, lon), dist=dist_network, network_type='drive')
        if 'MOTOR' in modes_needed: graphs['MOTOR'] = graphs['DRIVE']
        if 'MOBIL' in modes_needed: graphs['MOBIL'] = graphs['DRIVE']

    G_main = graphs.get('DRIVE', graphs.get('BERJALAN'))
    nodes, edges = ox.graph_to_gdfs(G_main)

    # ==========================================
    # 4. FUNGSI HELPER (Nested agar bisa akses G_main dan graphs)
    # ==========================================
    def validate_street_type(check_lat, check_lon, api_key=None):
        u, v, key = ox.distance.nearest_edges(G_main, X=check_lon, Y=check_lat)
        hw = G_main.get_edge_data(u, v, key).get('highway', 'unclassified')
        if isinstance(hw, list): hw = hw[0]

        st_type = 'STREET'
        if hw in ['trunk', 'primary', 'primary_link']: st_type = 'MAINSTREET'
        elif hw in ['secondary', 'tertiary']: st_type = 'SUBSTREET'

        if api_key and USE_GOOGLE_API:
            try:
                url = f"https://maps.googleapis.com/maps/api/geocode/json?latlng={check_lat},{check_lon}&key={api_key}"
                res = requests.get(url).json()
                if res['status'] == 'OK':
                    types = res['results'][0]['types']
                    if 'route' in types and st_type == 'STREET':
                        st_type = 'SUBSTREET'
            except: pass
        return st_type

    TARGET_STREET_TYPE = validate_street_type(lat, lon, API_KEY)
    street_ranks = {'STREET': 1, 'SUBSTREET': 2, 'MAINSTREET': 3}
    target_rank = street_ranks.get(TARGET_STREET_TYPE, 1)
    allowed_ranks = [target_rank, target_rank + 1]
    allowed_types = [k for k, v in street_ranks.items() if v in allowed_ranks]

    def get_isochrone_convex_hull(hull_lat, hull_lon, time_mins, mode):
        G = graphs[mode]
        speed_kmh = SPEED_DICT[mode]
        weight_attr = f"time_sec_{mode}"

        edge_data = list(G.edges(data=True))
        if len(edge_data) > 0:
            sample_dict = edge_data[0][-1]
            if weight_attr not in sample_dict:
                for u, v, k, data in G.edges(data=True, keys=True):
                    length = data.get('length', 1.0)
                    data[weight_attr] = length / (speed_kmh * 1000 / 3600)

        center_node = ox.distance.nearest_nodes(G, hull_lon, hull_lat)
        subgraph = nx.ego_graph(G, center_node, radius=time_mins * 60, distance=weight_attr)
        node_points = [Point((data['x'], data['y'])) for node, data in subgraph.nodes(data=True)]

        if len(node_points) >= 3:
            poly = gpd.GeoSeries(node_points, crs='EPSG:4326').unary_union.convex_hull
            return gpd.GeoSeries([poly], crs='EPSG:4326').to_crs('EPSG:3857').iloc[0]
        return Point(0,0)

    # ==========================================
    # 5. MENARIK KOMPETITOR & CLONE
    # ==========================================
    places_data = []
    if USE_GOOGLE_API:
        url_places = "https://places.googleapis.com/v1/places:searchText"
        headers = {"Content-Type": "application/json", "X-Goog-Api-Key": API_KEY, "X-Goog-FieldMask": "places.displayName,places.location"}
        search_queries = ['Indomaret', 'Alfamart', 'Alfamidi', 'Alfa Express', 'Family Mart', 'O!Save', 'Koperasi Desa Merah Putih', 'Kopdes']

        for query in search_queries:
            payload = {"textQuery": query, "locationBias": {"circle": {"center": {"latitude": lat, "longitude": lon}, "radius": float(radius2)}}}
            resp = requests.post(url_places, headers=headers, json=payload)

            if resp.status_code == 200 and 'places' in resp.json():
                for place in resp.json()['places']:
                    name = place.get('displayName', {}).get('text', query)
                    p_lat, p_lon = place['location']['latitude'], place['location']['longitude']

                    dist = Point(p_lon, p_lat).distance(pt_target) * 111320
                    if dist <= radius2:
                        st_type = validate_street_type(p_lat, p_lon, API_KEY)
                        if st_type in allowed_types:
                            b_type = 'Clone' if 'indomaret' in name.lower() else 'Competitor'
                            places_data.append({'name': name, 'type': b_type, 'lat': p_lat, 'lon': p_lon, 'street_type': st_type})

    df_places = pd.DataFrame(places_data).drop_duplicates(subset=['lat', 'lon']) if places_data else pd.DataFrame()
    df_comps = df_places[df_places['type'] == 'Competitor'] if not df_places.empty else pd.DataFrame()
    df_clones = df_places[df_places['type'] == 'Clone'] if not df_places.empty else pd.DataFrame()

    # ==========================================
    # 6. MEMBENTUK POLYGON ISOCHRONE
    # ==========================================
    poly_iso_target = get_isochrone_convex_hull(lat, lon, iso_time_target, iso_mode_target)

    poly_iso_comps = []
    if not df_comps.empty:
        for _, r in df_comps.iterrows():
            poly_iso_comps.append(get_isochrone_convex_hull(r['lat'], r['lon'], iso_time_comp, iso_mode_comp))
    union_poly_comp = gpd.GeoSeries(poly_iso_comps).unary_union if poly_iso_comps else Point(0,0)

    poly_iso_clones = []
    if not df_clones.empty:
        for _, r in df_clones.iterrows():
            poly_iso_clones.append(get_isochrone_convex_hull(r['lat'], r['lon'], iso_time_clone, iso_mode_clone))
    union_poly_clone = gpd.GeoSeries(poly_iso_clones).unary_union if poly_iso_clones else Point(0,0)

    # ==========================================
    # 7. ZONASI EKSKLUSI & MENARIK BANGUNAN GEE
    # ==========================================
    tags_exclude = {
        'amenity': ['school', 'hospital', 'clinic', 'place_of_worship', 'police'],
        'building': ['school', 'hospital', 'commercial', 'retail', 'office'],
        'shop': ['mall']
    }
    try:
        osm_ex_areas = ox.features_from_point((lat, lon), tags=tags_exclude, dist=radius2+200)
        osm_ex_areas = osm_ex_areas[osm_ex_areas.geometry.type.isin(['Polygon', 'MultiPolygon'])].to_crs('EPSG:3857')
        exclusion_zone_osm = osm_ex_areas.geometry.buffer(15).unary_union
    except:
        exclusion_zone_osm = Point(0,0)

    bounds_geom = gdf_center_metric.buffer(radius2 + 500).to_crs('EPSG:4326').iloc[0]
    roi_ee = ee.Geometry.Polygon(list(bounds_geom.exterior.coords))
    buildings_fc = ee.FeatureCollection('GOOGLE/Research/open-buildings/v3/polygons').filterBounds(roi_ee)

    try:
        gdf_buildings = gpd.read_file(buildings_fc.getDownloadURL(filetype='geojson'))
    except:
        gdf_buildings = gpd.GeoDataFrame()

    if gdf_buildings.empty:
        print("Tidak ada bangunan ditemukan di GEE atau gagal mengunduh.")
        bldg_bersih = gpd.GeoDataFrame()
    else:
        gdf_buildings['area_m2'] = gdf_buildings.get('area_in_meters', gdf_buildings.get('area_m2', 1))
        bldgs_proj = gdf_buildings.to_crs('EPSG:3857')
        bldgs_proj['geometry_polygon'] = bldgs_proj.geometry

        # Eksklusi Area Publik
        bldgs_proj = bldgs_proj[~bldgs_proj.geometry.intersects(exclusion_zone_osm)].copy()
        bldgs_proj.geometry = bldgs_proj.centroid
        bldgs_proj['tipe_residensial'] = 'rumah'
        bldg_bersih = bldgs_proj.set_geometry('geometry_polygon').drop(columns=['geometry']).rename_geometry('geometry')

    # ==========================================
    # 8. PERHITUNGAN HUFF MODEL
    # ==========================================
    if not bldg_bersih.empty:
        if 'building:levels' not in bldg_bersih.columns:
            bldg_bersih['building:levels'] = 1
        bldg_bersih['levels_num'] = pd.to_numeric(bldg_bersih['building:levels'], errors='coerce').fillna(1)
        bldg_bersih['area_num'] = pd.to_numeric(bldg_bersih['area_m2'], errors='coerce').fillna(1)

        val_rumah = (bldg_bersih['area_num'] * bldg_bersih['levels_num'] / 45) * 0.7
        bldg_bersih['KK_Total'] = np.maximum(1, np.round(val_rumah))

        bldg_3857 = bldg_bersih.copy()
        bldg_bersih['dist_to_target'] = bldg_3857.geometry.distance(center_geom_metric)
        bldg_bersih = bldg_bersih[bldg_bersih['dist_to_target'] <= radius2].copy()
        bldg_3857 = bldg_3857.loc[bldg_bersih.index]

        LAMBDA_DIST = 2.0
        GAMMA_ATTR = 1.0
        ATTR_TARGET = 1.0
        ATTR_COMPETITOR = 1.0
        ATTR_CLONE = 1.0

        bldg_bersih['U_Target'] = (ATTR_TARGET ** GAMMA_ATTR) / ((bldg_bersih['dist_to_target'] + 1) ** LAMBDA_DIST)
        bldg_bersih['U_Competitors_Total'] = 0.0

        if not df_places.empty:
            for idx, row in df_places.iterrows():
                pt_comp = gpd.GeoSeries([Point(row['lon'], row['lat'])], crs='EPSG:4326').to_crs('EPSG:3857').iloc[0]
                dist_to_comp = bldg_3857.geometry.distance(pt_comp) + 1
                attr_score = ATTR_CLONE if row['type'] == 'Clone' else ATTR_COMPETITOR
                u_comp = (attr_score ** GAMMA_ATTR) / (dist_to_comp ** LAMBDA_DIST)
                bldg_bersih['U_Competitors_Total'] += u_comp

        bldg_bersih['U_Total_All'] = bldg_bersih['U_Target'] + bldg_bersih['U_Competitors_Total']
        bldg_bersih['Prob_Target'] = bldg_bersih['U_Target'] / bldg_bersih['U_Total_All']
        bldg_bersih['KK_Expected_Aman'] = bldg_bersih['Prob_Target'] * bldg_bersih['KK_Total']

        conds = [
            bldg_bersih['Prob_Target'] >= 0.50,
            (bldg_bersih['Prob_Target'] >= 0.20) & (bldg_bersih['Prob_Target'] < 0.50),
            bldg_bersih['Prob_Target'] < 0.20
        ]
        choices = ['#32CD32', '#FFD700', '#B2054C']
        bldg_bersih['map_color'] = np.select(conds, choices, default='#D3D3D3')

    # ==========================================
    # 9. KUADRAN & GROUPING DATA
    # ==========================================
    if not bldg_bersih.empty:
        bldg_bersih = bldg_bersih.to_crs('EPSG:4326')
        cy, cx = bldg_bersih.centroid.y, bldg_bersih.centroid.x
        cond_q1 = (cy > lat) & (cx > lon)
        cond_q2 = (cy <= lat) & (cx > lon)
        cond_q3 = (cy <= lat) & (cx <= lon)

        bldg_bersih['Kuadran'] = np.select(
            [cond_q1, cond_q2, cond_q3],
            ["Area 1 : Utara - Timur", "Area 2 : Timur - Selatan", "Area 3 : Selatan - Barat"],
            default="Area 4 : Barat - Utara"
        )

        if not edges.empty:
            edges_proj = edges.to_crs('EPSG:3857')
            edges_proj['geometry'] = edges_proj.geometry.buffer(30)
            bldg_proj = bldg_bersih.to_crs('EPSG:3857')

            if 'name' in edges.columns:
                joined_rd = gpd.sjoin(bldg_proj, edges_proj[['name', 'geometry']], how='left', predicate='intersects')
                joined_rd = joined_rd[~joined_rd.index.duplicated(keep='first')]
                joined_rd['name'] = joined_rd['name'].apply(lambda x: x[0] if isinstance(x, list) else x)
                bldg_bersih['Nama_Jalan'] = joined_rd['name'].fillna('Jalan Tanpa Nama')
            else:
                bldg_bersih['Nama_Jalan'] = 'Jalan Tanpa Nama'

        tabel_kk = bldg_bersih.groupby(['Kuadran', 'Nama_Jalan']).apply(
            lambda x: pd.Series({
                f'TOTAL KK Fisik': x['KK_Total'].sum(),
                f'EKSPEKTASI KK (Huff Model)': np.round(x['KK_Expected_Aman'].sum(), 1)
            })
        ).reset_index()
    else:
        tabel_kk = pd.DataFrame()

    # ==========================================
    # 10. MENYIAPKAN DATAFRAME UNTUK OUTPUT
    # ==========================================
    # A. DataFrame Toko Kompetitor
    if not df_places.empty:
        df_places_print = df_places.copy()
        df_places_print['Poin(Lat, Long)'] = df_places_print.apply(lambda r: f"{r['lat']:.5f}, {r['lon']:.5f}", axis=1)
        df_places_print = df_places_print[['name', 'type', 'Poin(Lat, Long)', 'street_type']]
        df_places_print.columns = ['Nama Toko', 'Tipe', 'Poin(Lat, Long)', 'Tipe Jalan']
    else:
        df_places_print = pd.DataFrame(columns=['Nama Toko', 'Tipe', 'Poin(Lat, Long)', 'Tipe Jalan'])

    # B. DataFrame Coverage
    if not tabel_kk.empty:
        tabel_kk_print = tabel_kk[tabel_kk['EKSPEKTASI KK (Huff Model)'] > 0].copy()
        tabel_kk_print = tabel_kk_print.sort_values(by=['Kuadran', 'Nama_Jalan'])
    else:
        tabel_kk_print = pd.DataFrame(columns=['Kuadran', 'Nama_Jalan', 'TOTAL KK Fisik', 'EKSPEKTASI KK (Huff Model)'])

    # ==========================================
    # 11. MEMBANGUN FOLIUM MAP
    # ==========================================
    m = folium.Map(location=[lat, lon], zoom_start=15)
    folium.TileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', attr='Esri', name='Esri Satellite', overlay=False, control=True).add_to(m)
    folium.TileLayer('OpenStreetMap', name='Jalan Raya').add_to(m)

    def add_isochrone_to_map(gdf_geom_3857, map_obj, fill_color, border_color, name="Layer"):
        if not gdf_geom_3857.is_empty:
            gdf = gpd.GeoDataFrame(geometry=[gdf_geom_3857], crs='EPSG:3857').to_crs('EPSG:4326')
            folium.GeoJson(
                gdf, name=name,
                style_function=lambda x, fc=fill_color, bc=border_color: {
                    'fillColor': fc, 'color': bc, 'weight': 3, 'fillOpacity': 0.15
                }
            ).add_to(map_obj)

    folium.GeoJson(gpd.GeoDataFrame(geometry=[buffer_radius_2], crs='EPSG:4326'), style_function=lambda x: {'color': '#E1E100', 'fillColor': 'none', 'weight': 3, 'dashArray': '5,5'}, name=f'Radius {radius2}m').add_to(m)
    folium.GeoJson(gpd.GeoDataFrame(geometry=[buffer_radius_1], crs='EPSG:4326'), style_function=lambda x: {'color': '#063B00', 'fillColor': 'none', 'weight': 3, 'dashArray': '5,5'}, name=f'Radius {radius1}m').add_to(m)

    add_isochrone_to_map(poly_iso_target, m, '#00FFFF', '#0000FF', f'Isochrone Toko Kita (< {iso_time_target}m)')
    add_isochrone_to_map(union_poly_comp, m, '#FF9999', '#FF0000', f'Isochrone Kompetitor (< {iso_time_comp}m)')
    add_isochrone_to_map(union_poly_clone, m, '#FFD700', '#FFA500', f'Isochrone Clone (< {iso_time_clone}m)')

    if not bldg_bersih.empty:
        bldg_bersih['geometry'] = bldg_bersih['geometry'].simplify(tolerance=0.00005, preserve_topology=True)
        for color_val in bldg_bersih['map_color'].unique():
            if color_val == '#D3D3D3': continue
            subset = bldg_bersih[bldg_bersih['map_color'] == color_val]
            folium.GeoJson(
                subset,
                style_function=lambda x, c=color_val: {'color': 'none', 'fillColor': c, 'fillOpacity': 0.85},
                name=f'Residensial (Warna: {color_val})'
            ).add_to(m)

    if not df_places.empty:
        for idx, row in df_places.iterrows():
            icon_color = 'red' if row['type'] == 'Competitor' else 'blue'
            icon_type = 'shopping-cart' if row['type'] == 'Competitor' else 'copy'
            folium.Marker([row['lat'], row['lon']], tooltip=f"{row['name']}", icon=folium.Icon(color=icon_color, icon=icon_type, prefix='fa')).add_to(m)

    folium.Marker([lat, lon], tooltip="TOKO KITA", icon=folium.Icon(color='purple', icon='star', prefix='fa')).add_to(m)

    legend_html = f'''
    <div style="position: fixed; bottom: 30px; left: 30px; width: 380px; height: 420px; border:2px solid grey; z-index:9999; font-size:13px; background-color:white; padding: 15px; opacity: 0.95; border-radius: 8px;">
        <h4 style="margin-top:0; font-family: Arial;"><b>Legend: Catchment Area</b></h4>
        <i class="fa fa-star" style="color:purple; font-size:16px;"></i> 1. Titik Toko Utama<br>
        <i class="fa fa-shopping-cart" style="color:red; font-size:16px;"></i> 2. Titik Toko Kompetitor<br>
        <i class="fa fa-copy" style="color:blue; font-size:16px;"></i> 3. Titik Toko Clone<br><br>

        <b>Radius Jarak Lurus:</b><br>
        <i style="background:#E1E100;width:20px;height:3px;display:inline-block; border-top: 2px dashed white;"></i> 4. Radius {radius2}m Toko<br>
        <i style="background:#063B00;width:20px;height:3px;display:inline-block; border-top: 2px dashed white;"></i> 5. Radius {radius1}m Toko<br><br>

        <b>Zona Waktu Tempuh Riil (Isochrone):</b><br>
        <i style="background:rgba(0,255,255,0.25); border: 2px solid #0000FF; width:15px;height:15px;display:inline-block;"></i> 6. Radius Isochrone < {iso_time_target} Menit Toko Kita ({iso_mode_target})<br>
        <i style="background:rgba(255,215,0,0.25); border: 2px solid #FFA500; width:15px;height:15px;display:inline-block;"></i> 7. Radius Isochrone < {iso_time_clone} Menit Toko Clone ({iso_mode_clone})<br>
        <i style="background:rgba(255,153,153,0.25); border: 2px solid #FF0000; width:15px;height:15px;display:inline-block;"></i> 8. Radius Isochrone < {iso_time_comp} Menit Kompetitor ({iso_mode_comp})<br><br>

        <b>Peluang Market Share (Huff Model):</b><br>
        <i style="background:#32CD32;width:15px;height:15px;display:inline-block; border-radius: 3px;"></i> Peluang > 50% (Dominan ke Kita)<br>
        <i style="background:#FFD700;width:15px;height:15px;display:inline-block; border-radius: 3px;"></i> Peluang 20% - 50% (Bersaing)<br>
        <i style="background:#B2054C;width:15px;height:15px;display:inline-block; border-radius: 3px;"></i> Peluang < 20% (Didominasi Lawan)
    </div>
    '''
    m.get_root().html.add_child(folium.Element(legend_html))
    folium.LayerControl().add_to(m)

    # ==========================================
    # 12. GENERATE KML STRING (MOCKUP/PLACEHOLDER)
    # ==========================================
    # Di script asli tidak ada logic export ke KML, sehingga saya sisipkan XML dummy.
    # Anda bisa memanfaatkan fiona/geopandas untuk mengonversi bldg_bersih.to_file("data.kml", driver="KML")
    kml_data = '<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>Coverage Map</name></Document></kml>'

    return df_places_print, tabel_kk_print, m, kml_data
